apiVersion: apps/v1
kind: Deployment
metadata:
    name: astral-kerykeion
spec:
    replicas: 1
    selector:
        matchLabels:
            name: astral-kerykeion
    template:
        metadata:
            labels:
                name: astral-kerykeion
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
                fsGroup: 10001
                seccompProfile:
                    type: RuntimeDefault
            containers:
                - name: astral-kerykeion
                  image: ghcr.io/talaman/astral-kerykeion:${{ github.sha }}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8000
                  securityContext:
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      capabilities:
                          drop:
                              - ALL
                  volumeMounts:
                      - name: tmp
                        mountPath: /tmp
                  resources:
                    requests:
                        memory: 200Mi
                    limits:
                        memory: 512Mi
            volumes:
              - name: tmp
                emptyDir: {}
            imagePullSecrets:
              - name: github-container-registry
